### ISSUE TITLE
Uppercase letters in search field

### ISSUE THREAD

**Issue by dubicube** [securingdata/smartsafe-client-desktop#1]
Writing any uppercase letters in search field  gives no results (version 0.9.1)

**Comment by dubicube** [comment]
Variable "newValue" should also be converted to lowercase to fix the issue:

https://github.com/securingdata/smartsafe-client-desktop/blob/9151d9c12d03b9586f86d61cde2485b025bc8ced/src/main/java/smartsafe/view/GlobalView.java#L213

A more sophisticated search function would be appreciable to get results even with a typo in search text.

**Comment by securingdata** [comment]
Fixed in version 0.9.3
