### ISSUE TITLE
UI frozen when generating a random password without special characters

### ISSUE THREAD

**Issue by dubicube** [securingdata/smartsafe-client-desktop#12]
Client version: 1.0.5
OS: Windows 10

Steps to produce:
- Goto "Help" -> "Preferences"
- Remove all special characters in "Special character set" text field
- Save preferences by clicking "ok"
- Click "Create a new entry"
- For password field, click "Random"
- Enable "Include special characters" checkbox
- Click "Generate"
- Enjoy your frozen UI :)

**Comment by securingdata** [comment]
Fixed in version 1.0.6
