### ISSUE TITLE
Fatal error when trying to open another card reader

### ISSUE THREAD

**Issue by dubicube** [securingdata/smartsafe-client-desktop#9]
For one of my PC, I have a built-in card reader. When I launch the client, to unlock the key with password I have to choose between the built-in card reader of my PC and the external card reader from SmartSafe.
- Firstly, the client does not memorize the previous card reader selected: I have to always switch from my internal card reader to the external one.
- Secondly, if I try to put a password with my internal card reader, I get th dialog box "Fatal error. Oops an error occured". I can click "ok", but then all the UI is frozen. I would expect the UI to print a proper error message for this case, and to be able to change the card reader selected to enter the password on another card reader.

**Comment by securingdata** [comment]
Fixed in 1.0.3 version

- concerning previous selected reader: feature was present but not working because of a bug (now corrected)
- now handling case of reader that does not have a card
